version: 2.1
orbs:
  node: circleci/node@5.2.0
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - node/run:
          name: build_application
          pre-steps:
            - checkout
          post-steps:
            - run:
                name: Build Application
                command: npm run build
      - cypress/run:
          requires:
            - build_application
          pre-steps:
            - checkout
          start-command: npm start
          cypress-command: 'npx cypress run --record --parallel'
          parallelism: 2
          filters:
            branches:
              only:
                - staging
