version: 2.1
orbs:
  node: circleci/node@5.2.0
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          pre-steps:
            - checkout
            - run: npm ci
            - run: npm run build
          start-command:  npm start
          cypress-command: 'npx cypress run --record  --browser chrome baseUrl=https://staging-pnbs.vercel.app'
          parallelism: 2
          filters:
            branches:
              only:
                - staging
