version: 2.1
orbs:
  node: circleci/node@5.2.0
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          pre-steps:
            - checkout
          start-command:  npm run build && npm start
          cypress-command: 'npx cypress run'
          parallelism: 2
          filters:
            branches:
              only:
                - staging
