version: 2.1
orbs:
  node: circleci/node@5.2.0
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          pre-steps:
            - checkout
            - run: npm ci
            - run: npm run build
            - run: npm run start:cypress
          cypress-command: 'npx cypress run --record'
          parallelism: 2
          filters:
            branches:
              only:
                - staging
